FROM registry.access.redhat.com/ubi9/go-toolset@sha256:e91cbbd0b659498d029dd43e050c8a009c403146bfba22cbebca8bcd0ee7925f AS build-env
USER root
WORKDIR /ct_server
RUN git config --global --add safe.directory /ct_server
COPY hack/build-assets/certificate-transparency-go-1.1.6/certificate-transparency-go-1.1.6.tar.gz /ct_server/
RUN tar -zxvf certificate-transparency-go-1.1.6.tar.gz
WORKDIR /ct_server/certificate-transparency-go-1.1.6/trillian/ctfe/ct_server
RUN go build ./

# Install server
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:9c810eccada0cc6f25b46eeeea4516bab01828faef4fdd2fe49c760518b90dd1
COPY --from=build-env /ct_server/certificate-transparency-go-1.1.6/trillian/ctfe/ct_server/ct_server /usr/local/bin/ct_server
RUN chown root:0 /usr/local/bin/ct_server && chmod g+wx /usr/local/bin/ct_server

#Configure home directory
ENV HOME=/home
RUN chgrp -R 0 /${HOME} && chmod -R g=u /${HOME}

WORKDIR ${HOME}

LABEL description="The binary responsible for providing the Certificate Transparency (CT) log server."
LABEL io.k8s.description="The binary responsible for providing the Certificate Transparency (CT) log server."
LABEL io.k8s.display-name="CT server container image for Red Hat Trusted Artifact Signer."
LABEL io.openshift.tags="CT-server, Red Hat trusted artifact signer."
LABEL summary="Provides the CT-server binary."

# Set the binary as the entrypoint of the container
ENTRYPOINT ["ct_server"]