FROM registry.access.redhat.com/ubi9/go-toolset@sha256:7e49e105a854749d67e5e02fb4069b48bd50445098c780b7f808cc351dee2589 AS build-env
USER root
WORKDIR /ct_server
RUN git config --global --add safe.directory /ct_server
COPY hack/build-assets/certificate-transparency-go-1.1.6.tar.gz /ct_server/
RUN tar -zxvf certificate-transparency-go-1.1.6.tar.gz
WORKDIR /ct_server/certificate-transparency-go-1.1.6/trillian/ctfe/ct_server
RUN go build ./

# Install server
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:93d357bf8fae4a4965515898504d3c45b7421a56fc45fdd52651535a25af1023
COPY --from=build-env /ct_server/certificate-transparency-go-1.1.6/trillian/ctfe/ct_server/ct_server /usr/local/bin/ct_server
RUN chown root:0 /usr/local/bin/ct_server && chmod g+wx /usr/local/bin/ct_server

#Configure home directory
ENV HOME=/home
RUN chgrp -R 0 /${HOME} && chmod -R g=u /${HOME}

WORKDIR ${HOME}

LABEL description="The binary responsible for providing the Certificate Transparency (CT) log server."
LABEL io.k8s.description="The binary responsible for providing the Certificate Transparency (CT) log server."
LABEL io.k8s.display-name="CT server container image for Red Hat Trusted Artifact Signer."
LABEL io.openshift.tags="CT-server, Red Hat trusted artifact signer."
LABEL summary="Provides the CT-server binary."
LABEL com.redhat.component="ct-server"

# Set the binary as the entrypoint of the container
ENTRYPOINT ["ct_server"]
